version: '3.3'

services:

  # MariaDB
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: hackme_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: php
    networks:
      - mynet

  # Redis
  myredis:
    image: redis:latest
    networks:
      - mynet

  # PHP-FPM
  myphp:
    image: myphp:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000
    depends_on:
      - mysql
      - myredis
    networks:
      - mynet

  # Nginx
  mynginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - myphp
    networks:
      - mynet

  # phpMyAdmin
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8082:80"
    networks:
      - mynet

networks:
  mynet:
    driver: overlay

